// Code generated by go generate; DO NOT EDIT.
package digen

import (
	di_import_3 "github.com/dimes/dihedral/internal/example"
	di_import_1 "github.com/dimes/dihedral/internal/example/bindings"
	di_import_2 "github.com/dimes/dihedral/internal/example/dbstore"
)

type DihedralServiceComponent struct {
	github_com_dimes_dihedral_internal_example_bindings_ServiceModule   *di_import_1.ServiceModule
	github_com_dimes_dihedral_internal_example_dbstore_DBProviderModule *di_import_2.DBProviderModule
}

func NewDihedralServiceComponent(
	github_com_dimes_dihedral_internal_example_dbstore_DBProviderModule *di_import_2.DBProviderModule,
) *DihedralServiceComponent {
	return &DihedralServiceComponent{
		github_com_dimes_dihedral_internal_example_bindings_ServiceModule:   &di_import_1.ServiceModule{},
		github_com_dimes_dihedral_internal_example_dbstore_DBProviderModule: github_com_dimes_dihedral_internal_example_dbstore_DBProviderModule,
	}
}
func (d *DihedralServiceComponent) GetBoundType() di_import_1.BoundType {
	obj, err := d.provides_github_com_dimes_dihedral_internal_example_bindings_SpecificBoundType()
	if err != nil {
		panic(err)
	}
	return (di_import_1.BoundType)(obj)
}
func (d *DihedralServiceComponent) GetService() (*di_import_3.Service, error) {
	obj, err := factory_github_com_dimes_dihedral_internal_example_Service(d)
	if err != nil {
		var zeroValue *di_import_3.Service
		return zeroValue, err
	}
	return obj, nil
}
func (d *DihedralServiceComponent) GetServiceTimeout() (di_import_3.ServiceTimeout, error) {
	obj, err := d.provides_github_com_dimes_dihedral_internal_example_ServiceTimeout()
	if err != nil {
		var zeroValue di_import_3.ServiceTimeout
		return zeroValue, err
	}
	return obj, nil
}
