// Code generated by go generate; DO NOT EDIT.
package digen

import (
	target_pkg "github.com/dimes/dihedral/internal/example"
)

func factory_github_com_dimes_dihedral_internal_example_Service(d *DihedralServiceComponent) (*target_pkg.Service, error) {
	target := &target_pkg.Service{}
	param0, err := d.provides_github_com_dimes_dihedral_internal_example_ServiceTimeout()
	if err != nil {
		var zeroValue *target_pkg.Service
		return zeroValue, err
	}
	target.ServiceTimeout = param0
	param1, err := factory_github_com_dimes_dihedral_internal_example_dbstore_MemoryDBStore(d)
	if err != nil {
		var zeroValue *target_pkg.Service
		return zeroValue, err
	}
	target.DBStore = param1
	return target, nil
}
