// Code generated by go generate; DO NOT EDIT.
package digen

import (
	target_pkg "github.com/dimes/dihedral/internal/example/bindings"
)

func (d *DihedralServiceComponent) provides_github_com_dimes_dihedral_internal_example_bindings_SpecificBoundType() (target_pkg.SpecificBoundType, error) {
	returnValue := d.github_com_dimes_dihedral_internal_example_bindings_ServiceModule.ProvidesSpecificBoundType()
	return returnValue, nil
}
