// MAXMAX-provider Code generated by go generate; DO NOT EDIT.
package digen

import (
	target_pkg "github.com/dimes/dihedral/internal/example"
)

func (d *DihedralServiceComponent) provides_github_com_dimes_dihedral_internal_example_ServiceTimeout() (target_pkg.ServiceTimeout, error) {
	returnValue, err := d.github_com_dimes_dihedral_internal_example_bindings_ServiceModule.ProvidesServiceTimeout()
	return returnValue, err
}
