// Code generated by go generate; DO NOT EDIT.
package digen

import target_pkg "github.com/dimes/dihedral/internal/example/dbstore"

func (d *DihedralServiceComponent) provides_github_com_dimes_dihedral_internal_example_dbstore_Prefix() (target_pkg.Prefix, error) {
	return d.github_com_dimes_dihedral_internal_example_dbstore_DBProviderModule.ProvidesPrefix(), nil
}
